    letsencrypt-init:
        # https://stackoverflow.com/questions/39846649/how-to-use-lets-encrypt-with-docker-container-based-on-the-node-js-image
        image: certbot/certbot:v0.21.1
        env_file:
            - .env
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./web/letsencrypt/etc/letsencrypt:/etc/letsencrypt
            - ./web/letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt
            - ./web/letsencrypt/usr/share/nginx/html:/usr/share/nginx/html
        command: certonly -n -d ${CERT_DOMAIN} -m ${CERT_EMAIL} --standalone --agree-tos
    letsencrypt-renew:
        image: certbot/certbot:v0.21.1
        env_file:
            - .env
        volumes:
            - ./web/letsencrypt/etc/letsencrypt:/etc/letsencrypt
            - ./web/letsencrypt/var/lib/letsencrypt:/var/lib/letsencrypt
            - ./web/letsencrypt/usr/share/nginx/html:/usr/share/nginx/html
        command: certonly -n -d ${CERT_DOMAIN} --webroot -w /usr/share/nginx/html --agree-tos
