version: "3.3"
services:
    web:
        build:
            context: ./web
            dockerfile: web.Dockerfile
        env_file:
            - .env
        ports:
            - ${PORT_INSECURE}:${PORT_INSECURE}
            - ${PORT_SECURE}:${PORT_SECURE}
        depends_on:
            - api
        restart: on-failure
        volumes:
            - ./web:/usr/src/app

    api:
        build:
            context: ./api
            dockerfile: api.Dockerfile
        env_file:
            - .env
        ports:
            - 4000:4000
        depends_on:
            - db
            - mongo-express
        restart: on-failure
        volumes:
            - ./api:/usr/src/app

    mongo-express:
        logging:
            driver: none
        image: mongo-express:0.42
        ports:
            - ${PORT_MONGO_EXPRESS}:${PORT_MONGO_EXPRESS}
        depends_on:
            - db
        restart: on-failure
        environment:
            - "ME_CONFIG_OPTIONS_EDITORTHEME=ambiance"
            - "ME_CONFIG_MONGODB_SERVER=db"
            - "ME_CONFIG_BASICAUTH_USERNAME=root"
            - "ME_CONFIG_BASICAUTH_PASSWORD=123"

    db:
        image: mongo:3.6
        ports:
            - 27017:27017
        restart: on-failure
        volumes:
            - ./db/db:/data/db
        restart: always
