version: "3.4"
services:
    web:
        build:
            context: ./web
            dockerfile: ${ENV}.Dockerfile
        env_file:
            - .env
        ports:
            - "${PORT_INSECURE}:${PORT_INSECURE}"
            - "${PORT_SECURE}:${PORT_SECURE}"
        volumes:
            - ./web:/home/node/app
