version: "3.4"
services:
    web:
        build:
            context: ./web
            dockerfile: ${ENV}.Dockerfile
        command: yarn dev
        env_file:
            - .env
        ports:
            - "${PORT_INSECURE}:${PORT_INSECURE}"
            - "${PORT_SECURE}:${PORT_SECURE}"
            - "3000:3000"
        volumes:
            - ./web:/home/node/app
            - /home/node/app/node_modules
